import { Config } from "effect"

export function truthy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "true" || value === "1"
}

const copy = process.env["BIOINFORMATICA_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"]
const fff = process.env["BIOINFORMATICA_DISABLE_FFF"]

function enabledByExperimental(key: string) {
  return process.env[key] === undefined ? truthy("BIOINFORMATICA_EXPERIMENTAL") : truthy(key)
}

export const Flag = {
  OTEL_EXPORTER_OTLP_ENDPOINT: process.env["OTEL_EXPORTER_OTLP_ENDPOINT"],
  OTEL_EXPORTER_OTLP_HEADERS: process.env["OTEL_EXPORTER_OTLP_HEADERS"],

  BIOINFORMATICA_AUTO_HEAP_SNAPSHOT: truthy("BIOINFORMATICA_AUTO_HEAP_SNAPSHOT"),
  BIOINFORMATICA_GIT_BASH_PATH: process.env["BIOINFORMATICA_GIT_BASH_PATH"],
  BIOINFORMATICA_CONFIG: process.env["BIOINFORMATICA_CONFIG"],
  BIOINFORMATICA_CONFIG_CONTENT: process.env["BIOINFORMATICA_CONFIG_CONTENT"],
  BIOINFORMATICA_DISABLE_AUTOUPDATE: truthy("BIOINFORMATICA_DISABLE_AUTOUPDATE"),
  BIOINFORMATICA_ALWAYS_NOTIFY_UPDATE: truthy("BIOINFORMATICA_ALWAYS_NOTIFY_UPDATE"),
  BIOINFORMATICA_DISABLE_PRUNE: truthy("BIOINFORMATICA_DISABLE_PRUNE"),
  BIOINFORMATICA_DISABLE_TERMINAL_TITLE: truthy("BIOINFORMATICA_DISABLE_TERMINAL_TITLE"),
  BIOINFORMATICA_SHOW_TTFD: truthy("BIOINFORMATICA_SHOW_TTFD"),
  BIOINFORMATICA_DISABLE_AUTOCOMPACT: truthy("BIOINFORMATICA_DISABLE_AUTOCOMPACT"),
  BIOINFORMATICA_DISABLE_MODELS_FETCH: truthy("BIOINFORMATICA_DISABLE_MODELS_FETCH"),
  BIOINFORMATICA_DISABLE_MOUSE: truthy("BIOINFORMATICA_DISABLE_MOUSE"),
  BIOINFORMATICA_FAKE_VCS: process.env["BIOINFORMATICA_FAKE_VCS"],
  BIOINFORMATICA_SERVER_PASSWORD: process.env["BIOINFORMATICA_SERVER_PASSWORD"],
  BIOINFORMATICA_SERVER_USERNAME: process.env["BIOINFORMATICA_SERVER_USERNAME"],
  BIOINFORMATICA_DISABLE_FFF: fff === undefined ? process.platform === "win32" : truthy("BIOINFORMATICA_DISABLE_FFF"),

  // Experimental
  BIOINFORMATICA_EXPERIMENTAL_FILEWATCHER: Config.boolean("BIOINFORMATICA_EXPERIMENTAL_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  BIOINFORMATICA_EXPERIMENTAL_DISABLE_FILEWATCHER: Config.boolean("BIOINFORMATICA_EXPERIMENTAL_DISABLE_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  BIOINFORMATICA_EXPERIMENTAL_DISABLE_COPY_ON_SELECT:
    copy === undefined ? process.platform === "win32" : truthy("BIOINFORMATICA_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"),
  BIOINFORMATICA_MODELS_URL: process.env["BIOINFORMATICA_MODELS_URL"],
  BIOINFORMATICA_MODELS_PATH: process.env["BIOINFORMATICA_MODELS_PATH"],
  BIOINFORMATICA_DB: process.env["BIOINFORMATICA_DB"],

  BIOINFORMATICA_WORKSPACE_ID: process.env["BIOINFORMATICA_WORKSPACE_ID"],
  BIOINFORMATICA_EXPERIMENTAL_WORKSPACES: enabledByExperimental("BIOINFORMATICA_EXPERIMENTAL_WORKSPACES"),

  // Evaluated at access time (not module load) because tests, the CLI, and
  // external tooling set these env vars at runtime.
  get BIOINFORMATICA_DISABLE_PROJECT_CONFIG() {
    return truthy("BIOINFORMATICA_DISABLE_PROJECT_CONFIG")
  },
  get BIOINFORMATICA_EXPERIMENTAL_REFERENCES() {
    return enabledByExperimental("BIOINFORMATICA_EXPERIMENTAL_REFERENCES")
  },
  get BIOINFORMATICA_TUI_CONFIG() {
    return process.env["BIOINFORMATICA_TUI_CONFIG"]
  },
  get BIOINFORMATICA_CONFIG_DIR() {
    return process.env["BIOINFORMATICA_CONFIG_DIR"]
  },
  get BIOINFORMATICA_PURE() {
    return truthy("BIOINFORMATICA_PURE")
  },
  get BIOINFORMATICA_PERMISSION() {
    return process.env["BIOINFORMATICA_PERMISSION"]
  },
  get BIOINFORMATICA_PLUGIN_META_FILE() {
    return process.env["BIOINFORMATICA_PLUGIN_META_FILE"]
  },
  get BIOINFORMATICA_CLIENT() {
    return process.env["BIOINFORMATICA_CLIENT"] ?? "cli"
  },
}
